### ISSUE TITLE
Code Styling

### ISSUE THREAD

**Issue by jksmall0631** [mlimberg/snip-it#7]
Hey guys, 

Only a couple little suggestions, you've got quite a bit of commented out code in your master branch I'd get rid of all that. Also looks like you've got an app.onready in your main.js that doesn't seem to be doing anything. Hope that helps! 🐼🐳

**Comment by ejwill04** [comment]
Let's make sure we get our commented out of the base.

**Comment by ejwill04** [comment]
@bekahlundy @mlimberg
